//! Reference outputs for trantor-random, rendered as `RngVectors.roc`.
//!
//! - `golden`: Go's ChaCha8 (the C2SP chacha8rand reference), read from the
//!   committed `go/golden.txt`.
//! - `xoshiro`: xoshiro256++, `jump` and SplitMix64 seeding, from `rand_xoshiro`.
//! - `draws`: a model of every draw, written from the plan, over both.
//! - `uuids`: RFC 9562 layouts over those sources; the `uuid` crate formats.

pub mod draws;
pub mod golden;
pub mod roc;
pub mod uuids;
pub mod xoshiro;

use std::fmt::Write;
use std::path::PathBuf;

pub fn go_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("go")
}

pub fn golden_path() -> PathBuf {
    go_dir().join("golden.txt")
}

pub fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../components/random/RngVectors.roc")
}

/// The C2SP sample output, copied verbatim from the spec (2976 bytes).
pub fn c2sp_sample() -> Vec<u8> {
    let text = std::fs::read_to_string(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("c2sp/sample-output.hex"))
        .expect("read c2sp/sample-output.hex");
    roc::from_hex(&text.split_whitespace().collect::<String>())
}

pub fn render() -> String {
    let golden = golden::read();
    let mut out = String::new();
    out.push_str("## Generated by tests/vectors (`cargo run`); do not edit.\n");
    out.push_str("## ChaCha8: Go math/rand/v2 (tests/vectors/go/golden.txt).\n## xoshiro256++ and SplitMix64: rand_xoshiro 0.8.1.\n## Draws: a Rust model of the documented algorithms over those two sources.\n## UUIDs: that model, the RFC 9562 examples and the uuid crate 1.26.0.\n");
    out.push_str("RngVectors :: [].{\n");
    golden::render(&golden, &mut out);
    xoshiro::render(&mut out);
    draws::render(&golden, &mut out);
    uuids::render(&golden, &mut out);
    out.push_str("}\n");
    out
}

/// Appends `\tname : type\n\tname = value\n\n`.
pub fn def(out: &mut String, name: &str, ty: &str, value: &str) {
    writeln!(out, "\t{name} : {ty}\n\t{name} = {value}\n").unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn committed_vectors_are_current() {
        let committed = std::fs::read_to_string(vectors_path()).expect("read RngVectors.roc");
        assert!(committed == render(), "RngVectors.roc is stale: run `cargo run` in tests/vectors");
    }

    #[test]
    fn go_matches_the_c2sp_sample_output() {
        let golden = golden::read();
        let stream = &golden.streams[0];
        assert_eq!(stream.seed, *b"ABCDEFGHIJKLMNOPQRSTUVWXYZ123456");
        let sample = c2sp_sample();
        assert_eq!(sample.len(), 2976);
        let words: Vec<u64> = sample.chunks(8).map(|c| u64::from_le_bytes(c.try_into().unwrap())).collect();
        assert_eq!(words, stream.words[..372]);
    }
}
