// Reference outputs from Go's math/rand/v2 ChaCha8, the reference
// implementation of C2SP chacha8rand. `cargo run -- --regen-go` runs this and
// commits its stdout as golden.txt; `cargo test` reads the committed file, so
// Go is only needed to regenerate.
//
// Never calls Read: its byte buffering is not what Rng.bytes does, and a
// partial Read switches MarshalBinary to a longer "readbuf:" form.
package main

import (
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"math/rand/v2"
	"strings"
)

// seeds returns the C2SP sample seed, then three patterned seeds.
func seeds() [][32]byte {
	var c2sp [32]byte
	copy(c2sp[:], "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456")
	out := [][32]byte{c2sp}
	for k := 1; k <= 3; k++ {
		var s [32]byte
		for i := range s {
			s[i] = byte(i*37*k + 11*k)
		}
		out = append(out, s)
	}
	return out
}

func words(r *rand.ChaCha8, n int) string {
	parts := make([]string, n)
	for i := range parts {
		parts[i] = fmt.Sprintf("%016x", r.Uint64())
	}
	return strings.Join(parts, " ")
}

func main() {
	fmt.Println("# golden.txt: generated by tests/vectors/go (Go math/rand/v2 ChaCha8); do not edit.")
	all := seeds()

	// 372 words: three reseed cycles, the length of the C2SP sample output.
	for _, seed := range all {
		fmt.Printf("stream %x %s\n", seed, words(rand.NewChaCha8(seed), 372))
	}

	// fork: the parent draws `skip` words, then 4 more whose LE bytes seed the
	// child. Go has no fork; this is its definition.
	for _, skip := range []int{0, 5, 120, 124} {
		seed := all[1]
		parent := rand.NewChaCha8(seed)
		for range skip {
			parent.Uint64()
		}
		var childSeed [32]byte
		for i := range 4 {
			binary.LittleEndian.PutUint64(childSeed[i*8:], parent.Uint64())
		}
		child := rand.NewChaCha8(childSeed)
		fmt.Printf("fork %x %d child %s parent %s\n", seed, skip, words(child, 40), words(parent, 40))
	}

	// marshal: the state after `draws` words, and the 3 words that follow it
	// once Go has unmarshalled that state into a fresh generator.
	for _, draws := range []int{0, 1, 27, 28, 31, 32, 96, 123, 124, 125, 200, 248, 249} {
		seed := all[2]
		r := rand.NewChaCha8(seed)
		for range draws {
			r.Uint64()
		}
		state, err := r.MarshalBinary()
		if err != nil {
			panic(err)
		}
		resumed := rand.NewChaCha8([32]byte{})
		if err := resumed.UnmarshalBinary(state); err != nil {
			panic(err)
		}
		fmt.Printf("marshal %x %d %s %s\n", seed, draws, hex.EncodeToString(state), words(resumed, 3))
	}

	// unmarshal: whether Go accepts a hand-built 48-byte state by used count.
	for _, used := range []uint64{0, 124, 125, 1 << 40} {
		state := make([]byte, 48)
		copy(state, "chacha8:")
		binary.BigEndian.PutUint64(state[8:], used)
		copy(state[16:], all[3][:])
		ok := rand.NewChaCha8([32]byte{}).UnmarshalBinary(state) == nil
		fmt.Printf("unmarshal %s %t\n", hex.EncodeToString(state), ok)
	}
}
